name: Test

on: [pull_request, push, pull_request_target]

jobs:
  build:
    runs-on: windows-latest
    env:
      DOWNLOADPLATFORM: '${{ matrix.arch }}'
    permissions:
      contents: read
    strategy:
      matrix:
        go: [ '1.18', '1.23', 'stable' ]
        arch: [ 'x64', 'x86' ]
    steps:
      - name: 'Checkout Project'
        uses: actions/checkout@v4

      - name: 'Download COM Test Release'
        shell: pwsh
        run: Start-FileDownload "https://github.com/go-ole/test-com-server/releases/download/v1.0.2/test-com-server-${{ matrix.arch }}.zip"
      - name: 'Unzip COM Test Release'
        run: 7z e test-com-server-${{ matrix.arch }}.zip -oc:./ > NUL
      - name: 'Register Assembly'
        run: .\build\register-assembly.bat
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          check-latest: true
      - name: 'Go Version'
        run: go version
      - name: 'Go Guild'
        run: go build
      - name: Run tests
        run: go test