name: Test

on: [pull_request, push, pull_request_target]

jobs:
  download:
    runs-on: windows-latest
    permissions:
      contents: read
    steps:
      - name: 'Checkout Project'
        uses: actions/checkout@v4

      - name: 'Download COM Test Release'
        uses: robinraju/release-downloader@v1
        with:
          repository: 'go-ole/test-com-server'
          latest: true
          fileName: 'test-com-server-x32.zip'
          zipBall: true
          extract: true
      - name: 'List directory - DEBUG TO FIND TESTCOMServer'
        run: 'dir ${{ github.workspace }}'
      - name: 'Register Assembly'
        run: 'c:\Windows\Microsoft.NET\Framework\v4.0.30319\RegAsm.exe /codebase /nologo ${{ github.workspace }}\TestCOMServer.dll'

  build:
    runs-on: windows-latest
    needs: download
    permissions:
      contents: read
    strategy:
      matrix:
        go: [ '1.18', '1.23', 'stable' ]
        arch: [ 'arm', '386', 'mips', 'mipsle']
    env:
      GOARCH: ${{ matrix.arch }}
    steps:
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          check-latest: true
      - name: 'Go Version'
        run: go version
      - name: 'Go Guild'
        run: go build
      - name: Run tests
        run: go test