name: Test 64-bit Architectures

on: [pull_request, push, pull_request_target]

jobs:
  download:
    runs-on: windows-latest
    permissions:
      contents: read
    steps:
      - name: 'Checkout Project'
        uses: actions/checkout@v4

      - name: 'Download COM Test Release'
        uses: robinraju/release-downloader@v1
        with:
          repository: 'go-ole/test-com-server'
          latest: true
          fileName: 'test-com-server-x64.zip'
          out-file-path: 'test-com-server'
          zipBall: true
          extract: true
      - name: 'List directory - DEBUG TO FIND TESTCOMServer'
        run: 'dir ${{ github.workspace }}\test-com-server\x64'
      - name: 'Register Assembly'
        run: 'c:\Windows\Microsoft.NET\Framework64\v4.0.30319\RegAsm.exe /codebase /nologo ${{ github.workspace }}\test-com-server\x64\TestCOMServer.dll'

  build:
    runs-on: windows-latest
    needs: download
    permissions:
      contents: read
    strategy:
      matrix:
        go: [ '1.18', '1.23', 'stable' ]
        arch: [ 'amd64', 'arm64' ]
#        arch: [ 'amd64', 'arm64', 'loong64', 'mips64', 'mips64le', 'ppc64', 'ppc64le', 'riscv64', 's390x' ]
    env:
      GOARCH: ${{ matrix.arch }}
    steps:
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          check-latest: true
      - name: 'Go Version'
        run: go version
      - name: 'Go Guild'
        run: go build
      - name: Run tests
        run: go test